name: Merge wbfy
on:
  workflow_dispatch:
  schedule:
    - cron: 32 16,17 * * *
jobs:
  wbfy-merge:
    uses: WillBooster/reusable-workflows/.github/workflows/wbfy-merge.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
